dist: focal
language: c

os: linux

compiler: gcc

install:
  - sudo apt-get install valgrind
  - sudo apt-get install clang
  - sudo pip install cpplint

script:
#  - ./linters/run.sh
#  - mkdir test/test_output
  - mkdir build
  - cd build
  - cmake ..
  - make clean && make
  - valgrind --tool=memcheck --leak-check=full ./test/tests_tests

codecov:
  token: da3effde-9ccb-4281-a7d3-4b283cf00a6f

after_success:
  - bash <(curl -s https://codecov.io/bash)
