arch: amd64
os: linux
dist: focal

language: c

compiler: gcc

install:
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo pip install cpplint

script:
  - sh ./linters.sh
  - mkdir build && cd build
  - cmake ..
  - make
  - valgrind --tool=memcheck --leak-check=full ctest
  - python3 ../generator/number_generator.py
  - ./hw-2 data.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
