arch: amd64
os: linux
dist: focal

language: c

compiler: gcc

install:
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo pip install cpplint

script:
  - sh ./linters.sh
  - mkdir build && cd build
  - cmake ..
  - make clean && make
  - cd ../generator
  - python3 number_generator.py
  - cd ../build
  - valgrind --tool=memcheck --leak-check=full ctest
  - ./hw-2
  - cmake -DPARALLEL=ON ..
  - make clean && make
  - valgrind --tool=memcheck --leak-check=full ctest
  - ./hw-2

after_success:
  - bash <(curl -s https://codecov.io/bash)
