dist: focal
language: c

os: linux

compiler: gcc

install:
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo pip install cpplint

script:
  - cppcheck --inconclusive --enable=all --language=c include/*/*.h src/*.c
  - cpplint --extensions=c include/*/* src/*
  - mkdir build && cd build
  - cmake ..
  - make clean && make
  - valgrind --tool=memcheck --leak-check=full ctest

after_success:
  - bash <(curl -s https://codecov.io/bash)
