arch: amd64
os: linux
dist: focal

language: c

compiler: gcc

install:
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo pip install cpplint

script:
  - cppcheck --enable=all --language=c sum_lib/*/* metrics/*/* --suppress=missingInclude
  - cpplint --extensions=c sum_lib/*/* metrics/*/*
  - mkdir build && cd build
  - cmake ..
  - make clean && make
  - python3 ../generator/number_generator.py
  - valgrind --tool=memcheck --leak-check=full ctest
  - ./hw-2
  - cmake -DPARALLEL=ON ..
  - make clean && make
  - valgrind --tool=memcheck --leak-check=full ctest
  - ./hw-2

after_success:
  - bash <(curl -s https://codecov.io/bash)
